### ISSUE TITLE
Missing information for 1.2 source?

### ISSUE THREAD

**Issue by chrisaj** [RadeonOpenCompute/ROCm#26]
Using the given command to download the RoCM 1.2 source does not work:

$ repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-1.2.0

curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
fatal: Couldn't find remote ref refs/heads/roc-1.2.0
Unexpected end of command stream

**Comment by almson** [comment]
There is no `roc-1.2.0` branch, and this repo doesn't contain anything interesting. Maybe someone could answer where to get all of the sources.

**Comment by chrisaj** [comment]
The command I posted is taken directly from the readme

**Comment by almson** [comment]
Which readme?

**Comment by chrisaj** [comment]
https://github.com/RadeonOpenCompute/ROCm/blob/master/README.md

**Comment by almson** [comment]
Ah, yes. Someone from AMD will have to fix that. Looks like they meant to make the other repos as submodules of this repository.

**Comment by jedwards-AMD** [comment]
This has been corrected. A ROCm 1.2.0 branch is now available for use with the repo command.

**Comment by chrisaj** [comment]
Thanks!

**Comment by chrisaj** [comment]
Hmmm. Still no clean checkout:

$ repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-1.2.0
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Counting objects: 1, done
remote: Finding sources: 100% (54/54)
remote: Total 54 (delta 15), reused 54 (delta 15)
Unpacking objects: 100% (54/54), done.
From https://gerrit.googlesource.com/git-repo
   f97e72e..39252ba  master     -> origin/master
   203153e..39252ba  stable     -> origin/stable
 * [new tag]         v1.12.34   -> v1.12.34
Get https://github.com/RadeonOpenCompute/ROCm.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
remote: Counting objects: 138, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 138 (delta 0), reused 0 (delta 0), pack-reused 135
Receiving objects: 100% (138/138), 48.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (37/37), done.
From https://github.com/RadeonOpenCompute/ROCm
 * [new branch]      from-andres -> origin/from-andres
 * [new branch]      gh-pages   -> origin/gh-pages
 * [new branch]      master     -> origin/master
 * [new branch]      roc-1.0.0  -> origin/roc-1.0.0
 * [new branch]      roc-1.1.0  -> origin/roc-1.1.0
 * [new branch]      roc-1.1.1  -> origin/roc-1.1.1
 * [new branch]      roc-1.2.0  -> origin/roc-1.2.0
 * [new tag]         roc-1.0.0  -> roc-1.0.0


Doing a repo sync then fails in various ways:
$ repo sync
Fetching project rdma-perftest
Fetching project HIP-Examples
Fetching project HIP
Fetching project clang
fatal: Invalid refspec '+refs/heads//refs/tags/roc-1.2.0:refs/remotes/pctools-github//refs/tags/roc-1.2.0'
fatal: Invalid refspec '+refs/heads//refs/tags/roc-1.2.0:refs/remotes/roc-github//refs/tags/roc-1.2.0'
fatal: Invalid refspec '+refs/heads//refs/tags/roc-1.2.0:refs/remotes/roc-github//refs/tags/roc-1.2.0'
fatal: Invalid refspec '+refs/heads//refs/tags/roc-1.2.0:refs/remotes/pctools-github//refs/tags/roc-1.2.0'
.....

**Comment by arodrigx7** [comment]
There is an extra '/' in the refspec, I'll get it fix in a sec.

**Comment by arodrigx7** [comment]
Seems like Adrian beat me to it.

**Comment by jedwards-AMD** [comment]
Yes this has been fixed.

**Comment by chrisaj** [comment]
There is still a problem with the repo init:

repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-1.2.0
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Counting objects: 1, done
remote: Finding sources: 100% (54/54)
remote: Total 54 (delta 15), reused 54 (delta 15)
Unpacking objects: 100% (54/54), done.
From https://gerrit.googlesource.com/git-repo
   f97e72e..39252ba  master     -> origin/master
   203153e..39252ba  stable     -> origin/stable
 * [new tag]         v1.12.34   -> v1.12.34
Get https://github.com/RadeonOpenCompute/ROCm.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.

**Comment by chrisaj** [comment]
(Please let me know if there's a better way to report this kind of problem)

**Comment by arodrigx7** [comment]
Hey chisaj,

Can I trouble you to create gist with your full console log for this command:
https://gist.github.com/

If that is an error fetching clone.bundle it should be benign. The clone.bundle is used to optimize downloads of very large projects like the Android source code.

In this case you will see repo init has an exit code of 0 (success).

**Comment by arodrigx7** [comment]
For a bit more reference:
http://stackoverflow.com/questions/23300245/what-to-do-about-curl-clone-bundle-error-on-aosp-repo-sync

**Comment by chrisaj** [comment]
gist here: https://gist.github.com/chrisaj/e3a77e3b7145faf68413733db362c829

**Comment by arodrigx7** [comment]
That is the case I described above. Repo init actually completed successfully and the exit code status should be '0'.

You can proceed to run 'repo sync' to fetch all the code.

**Comment by chrisaj** [comment]
Thanks. I'm running the sync now. Seems to be working so far.
