### ISSUE TITLE
Valgind warnings

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#300]
I ran my opencl program against valgrind, and I get a number of 
`== Conditional jump or move depends on uninitialised value(s)`
warnings triggered  by `clEnqueueNDRangeKernel` and `clEnqueueWriteBuffer`

**Comment by gstoner** [comment]
We. are fixing this it was false positives

**Comment by gstoner** [comment]
@boxerab  Can you try the beta http://repo.radeon.com/misc/archive/beta/rocm-1.7.1.beta.4.tar.bz2  It support 4.13 Linux kernel   We fixed issue for Valgrind to fix the false positives in this release

**Comment by boxerab** [comment]
Still getting valgrind warnings with 1.7.2


==19355== Conditional jump or move depends on uninitialised value(s)
==19355==    at 0xAE7F74F: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE819E3: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE84C85: hsaKmtMapMemoryToGPU (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE877D3: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE7E185: hsaKmtCreateEvent (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAA00002: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA0A1C7: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA0B8A9: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9EEDA4: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9EEE03: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA093AD: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9EFD29: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355== 
==19355== Conditional jump or move depends on uninitialised value(s)
==19355==    at 0xAE7F74F: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE83887: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE84DC4: hsaKmtMapMemoryToGPUNodes (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xA9EB7DB: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA077F2: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA000C1: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA0A1EC: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA0B8A9: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9EEDA4: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9EEE03: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA093AD: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9EFD29: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355== 
==19355== Conditional jump or move depends on uninitialised value(s)
==19355==    at 0xAE7F74F: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE819E3: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE84C85: hsaKmtMapMemoryToGPU (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE87526: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE87AD6: hsaKmtCreateQueue (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xA9E6559: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9DFED9: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9E3F35: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA09448: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9EFD29: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0x70E6ACC: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70B2B12: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355== 
==19355== Conditional jump or move depends on uninitialised value(s)
==19355==    at 0xAE7F74F: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE819E3: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE87E6E: hsaKmtCreateQueue (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xA9E6559: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9DFED9: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9E3F35: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA09448: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9EFD29: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0x70E6ACC: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70B2B12: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70BF306: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x708FB7D: clGetPlatformIDs (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355== 
==19355== Conditional jump or move depends on uninitialised value(s)
==19355==    at 0xAE7F74F: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE83887: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE84DC4: hsaKmtMapMemoryToGPUNodes (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xA9E9878: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9EDE2B: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9EBC03: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA076AB: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9F28A1: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9E7779: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9E7A78: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA17334: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA17A4D: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355== 
==19355== Conditional jump or move depends on uninitialised value(s)
==19355==    at 0xAE7F74F: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE83887: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE84DC4: hsaKmtMapMemoryToGPUNodes (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xA9E9282: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9FC880: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0x70E3C81: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70F192C: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70E691A: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70E7443: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70B2B12: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70BF306: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x708FB7D: clGetPlatformIDs (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355== 
Platform found : Advanced Micro Devices, Inc.

Selected Platform Vendor : Advanced Micro Devices, Inc.
Device 0 : gfx803 Device ID is 0xca54a90
==19355== Syscall param rt_sigaction(act->sa_flags) points to uninitialised byte(s)
==19355==    at 0x559B48E: __libc_sigaction (sigaction.c:62)
==19355==    by 0x42D9C8: setup_signal_handler() (opj_compress.cpp:139)
==19355==    by 0x43A44B: plugin_main(int, char**, CompressInitParams*) (opj_compress.cpp:2015)
==19355==    by 0x438A88: main (opj_compress.cpp:1531)
==19355==  Address 0xffeff8c78 is on thread 1's stack
==19355== 
==19355== Conditional jump or move depends on uninitialised value(s)
==19355==    at 0xAE7F74F: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE838D5: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE84DC4: hsaKmtMapMemoryToGPUNodes (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xA9E8A0F: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9FC50C: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0x70F18FE: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70E4F8E: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70CE33E: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70CE405: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70C0574: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x70AE191: clEnqueueWriteBuffer (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x68E11F8: grk::BlockInfoExtractorOCL::init(grk::CompressedImage*, bool) (BlockInfoExtractorOCL.cpp:41)
==19355== 

Device memory allocated: 1964 MB

Creating program preprocess.cl from source
Building program preprocess.cl
Build Options are :  -I ./ -D PREPROCESSOR_KERNEL_DIM_X=8 -D PREPROCESSOR_KERNEL_DIM_Y=8 -D DC -D COLOUR_TRANSFORM -fno-bin-llvmir -fno-bin-amdil -fno-bin-source
==19355== Conditional jump or move depends on uninitialised value(s)
==19355==    at 0x8ADA9CD: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x8ADB48E: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x8AE7026: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x8AEA2D4: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x8ADC2DC: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x8ADF3D6: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x8AE06D1: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x8AE1900: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x8AE27BA: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x8AEABF0: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x919C1B9: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x919C2ED: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355== 
^C==19355== 
==19355== Process terminating with default action of signal 2 (SIGINT)
==19355==    at 0x559B269: raise (pt-raise.c:35)
==19355==    by 0x922A354: ??? (in /opt/rocm/opencl/lib/x86_64/libamdocl64.so)
==19355==    by 0x559B38F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.23.so)
==19355==    by 0x6144F46: ioctl (syscall-template.S:84)
==19355==    by 0xAE83F87: ??? (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAE7E42E: hsaKmtWaitOnMultipleEvents (in /opt/rocm/libhsakmt/lib/libhsakmt.so.1.0.7)
==19355==    by 0xAA0FAC2: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9FC005: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xAA0BAD1: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0xA9D6816: ??? (in /opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.7)
==19355==    by 0x55916B9: start_thread (pthread_create.c:333)
==19355==    by 0x614F41C: clone (clone.S:109)
==19355== 
==19355== HEAP SUMMARY:
==19355==     in use at exit: 720,062,422 bytes in 150,919 blocks
==19355==   total heap usage: 480,785 allocs, 329,866 frees, 868,397,694 bytes allocated
==19355== 
==19355== LEAK SUMMARY:
==19355==    definitely lost: 3,552 bytes in 53 blocks
==19355==    indirectly lost: 1,584 bytes in 33 blocks
==19355==      possibly lost: 294,896 bytes in 2,621 blocks
==19355==    still reachable: 719,762,390 bytes in 148,212 blocks
==19355==                       of which reachable via heuristic:
==19355==                         stdstring          : 410 bytes in 10 blocks
==19355==                         multipleinheritance: 20,632 bytes in 50 blocks
==19355==         suppressed: 0 bytes in 0 blocks
==19355== Rerun with --leak-check=full to see details of leaked memory
==19355== 
==19355== For counts of detected and suppressed errors, rerun with: -v
==19355== Use --track-origins=yes to see where uninitialised values come from
==19355== ERROR SUMMARY: 422 errors from 9 contexts (suppressed: 0 from 0)

**Comment by gstoner** [comment]
Your getting a false positive
